### ISSUE TITLE
logo.png not found

### ISSUE THREAD

**Issue by pidipy** [asgardex/asgard-exchange#224]
It's a small but nonetheless:

URL: https://testnet.asgard.exchange/swap

`https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xaD6D458402F60fD3Bd25163575031ACDce07538D/logo.png`

![image](https://user-images.githubusercontent.com/81856738/114005449-d6eb6c00-985f-11eb-9946-1516eeccb5d9.png)

**Comment by stuartkuentzel** [comment]
Hey @pidipy thanks for bringing up this issue. This actually expected behavior, since the ethereum assets are pointing to testnet contracts, and the trustwallet repo only has mainnet contracts listed. On mainnet, this shouldn't be an issue, and on the occasion that it throws a 404, the UI should catch it with a fallback '?' icon. Either way, thanks for testing it out before chaosnet, and if you notice anything else, feel free to open another issue.
