### ISSUE TITLE
RUNE/BTC LP deposit not showing, funds missing

### ISSUE THREAD

**Issue by andrewjmoser** [asgardex/asgard-exchange#261]
Deposited Rune and BTC LP on Asgardex, I am not seeing anything in the LP pool yet the BTC and Rune have been withdrawn from my wallet.   Here is the transaction ID.  7fdafe9fdea6653aa3630c03c24bc32dc65647615e6d79ccc4df5f994fce8003

**Comment by edwardjohansson** [comment]
Please see https://github.com/asgardex/asgard-exchange/issues/265

You can lookup your bitcoin address on https://www.blockchain.com/ (pop your btc address from your wallet in the search) and it's likely an unconfirmed transaction as the fee is too low. If it fails, your money should be automatically returned (well, technically, it'll be like the transaction never happened).

**Comment by stuartwk** [comment]
Hey @andrewjmoser, if this is still an issue, please try searching for the BTC pool in https://app.asgard.exchange/deposit-sym-recovery. This allows you to send a RUNE Withdraw transaction to the BTC pool, which will withdraw all successful and pending funds from the BTC pool.

Due to some xchain updates, RUNE transactions require a minimum of 3 RUNE in your wallet. The actual network fee + gas is much lower, it just uses that as a kind of safety net for the transaction to succeed. 

Also keep in mind, the BTC network fees right now might be quite high due to a decreased hash rate.
