### ISSUE TITLE
RUNE -BTC LP on Asgardex

### ISSUE THREAD

**Issue by wolfmalta** [asgardex/asgard-exchange#265]
Deposited Rune and BTC LP on Asgardex, not seeing anything in the LP pool yet the BTC and Rune have been withdrawn from my wallet. There is no transaction showing but funds are withdrawn. 
Thor address is thor1xfpzktfhj88fe8f7evf20f54m6wgze5f2r7e6q

**Comment by edwardjohansson** [comment]
Hi wolfmalta,
Thought I'd help (I'm not part of the team, just community)
I think it's an issue with low fees being defaulted for btc staking (same thing happened to me). Rest assured your funds are still there.

Your stake request for Rune is here:
https://viewblock.io/thorchain/address/thor1xfpzktfhj88fe8f7evf20f54m6wgze5f2r7e6q

However, the bitcoin portion has not completed:
https://www.blockchain.com/btc/address/bc1qppltp0qxxkmr7k8kkgqkpdq0zng2tzmuyhnyct
(you can see it there as unconfirmed)
If you're lucky, a bitcoin miner will confirm the transaction and you'll be staking.
Otherwise, it'll eventually be flushed out of the mempool and the funds will reappear back in your btc wallet (note, this could take about 3 days though). This happens with all btc transactions that have set the fee too low.

**Comment by edwardjohansson** [comment]
Quick update, I can see a pull request was committed to fix this:
https://github.com/asgardex/asgard-exchange/pull/262/commits/b7bd54709de459985895ad7aaea52f74bae9464c

Just need for it to be deployed to production. Unfortunately we will have to wait for the transaction to fail to try again (up to 3 days)

**Comment by stuartkuentzel** [comment]
@edwardjohansson thanks for addressing this! 
there's been an update to the code for new BTC transactions, but currently pending transactions might take some time. We're working on adding "speed up" functionality to get these transactions moving.

**Comment by edwardjohansson** [comment]
@stuartkuentzel excellent news!! 
Yes that would be helpful. I've used some btc accelerators (the free ones) to rebroadcast in the hopes it gets picked up. But would be great to have functionality to add to the fees (doublespend + higher fee) to get it through.

**Comment by edwardjohansson** [comment]
@wolfmalta 
Try this:
https://www.viabtc.com/tools/txaccelerator/
Enter your transaction hash (it is a046edc48d0b3adb3aa6065d3d2585f523e26b82aad7d9afe358f85798400de0 ) and click 'submit for free'.

They open up slots at the start of every hour for free acceleration (and it runs out of slots within a minute) - if you do it straight away at the start of a new hour you should get in.

**Comment by wolfmalta** [comment]
Thank you both for your time and advice. Much appreciated! I will look at this now...

**Comment by wolfmalta** [comment]
Issue is resolved. Thanks again!
