### ISSUE TITLE
Failed Adding Liquidity to ETH / RUNE pair, accepted ETH but rejected RUNE, no return of funds option?

### ISSUE THREAD

**Issue by nameless1one1** [asgardex/asgard-exchange#280]
Tried a few tests as follows yesterday...
+ Created wallet, added .1 ETH to it, Swapped .4664 ETH to RUNE token ALL AOK!
https://www.etherchain.org/account/0xaa0effd994e423ec489a4e90d94083532214bfff#txs

However, then...
- Attempted to add other .46 ETH and matching RUNE to Liquidity Pool, (surprisingly) accepted ETH but rejected RUNE?
- Prompt allowed retry on RUNE but no clear way to cancel overall transaction to return ETH?
- All retries to submit RUNE failed, eventually with weird Error ? (See image) 

Day later, ETH still not returned to wallet and no screens are available to access accepted ETH in (default/hidden) pool.
NOTE: Pool was not created before hand, so weird it even accepted ETH? or even allowed Liquidity add ability?

Q: How do I retrieve the ETH to wallet if it can't be accessed anywhere ? 

![THORasgardPoolFail](https://user-images.githubusercontent.com/82606011/114913442-2f39e500-9def-11eb-9407-4d3a848c7aa1.png)

**Comment by stuartkuentzel** [comment]
hey @nameless1one1 👋 , we believe this is an ongoing issue with the xchain/thorchain wallet basically saying that you have insufficient funds even though they exist. We'll have an interface ready soon to deposit the missing half, and you'll show up as a pool member, once the xchainjs updates have been made. Will drop a link once everything is deployed.

**Comment by stuartwk** [comment]
@nameless1one1 please try and withdraw your pending assets using https://app.asgard.exchange/deposit-sym-recovery. This sends a RUNE Withdraw deposit to the pool with the pending funds. This will withdraw all funds, both successful and pending, from the pool.

Keep in mind, due to some xchain/thorchain changes, you need a minimum of 3 RUNE in your wallet for any RUNE transactions. The fee/network gas won't use all of that, it's just a kind of safety net to ensure RUNE transactions succeed. 

For ETH, when the withdraw succeeds, you can see funds returned on etherscan in the "internal transactions" tab.

**Comment by stuartwk** [comment]
Closing this out as the issue seems inactive. @nameless1one1 if this is still an issue, feel free to reopen or create a new issue.

**Comment by code-ae** [comment]
I am currently experiencing the same issue, and having trouble connecting my Asgardex wallet to the '/deposit-sym-recovery' page.
Please advise on how i can proceed, appreciate any information, thank you.
