### ISSUE TITLE
After adding to BTC/RUNE, BTC shows 0 and RUNE balance is unchanged

### ISSUE THREAD

**Issue by djesys** [asgardex/asgard-exchange#289]
Hi!
As said, I added more BTC and RUNE to the pool in ASGARDEX and now my BTC Balance is 0 and my RUNE balance
remained unchanged. I am slightly panicing and I am now aware it might be because of the the cap.
It was a larger amount.. Please look into this, thanks.

BTC address is: bc1qqjr5twftctxf5u77wzvdks07p9gujql6dn97qz

This is the TX of the RUNE transaction  https://thorchain.net/#/txs/3652696429983DEEEFA6310EF89025201693A376732B5AB209EE19D22D330D7E

**Comment by stuartwk** [comment]
Hello @djesys 👋 , in the link you sent me, it says that the transaction has been refunded due to cap.
Searching for your address in https://thornode.thorchain.info/thorchain/pool/BTC.BTC/liquidity_providers, you can see that you are listed with pooled BTC. No pending RUNE or pending BTC.
It could also be taking some time to go through due to crazy BTC price fluctuations today. Please send over a screenshot if the issue is still happening. Additionally, please do not pool on THORChain at the moment due to cap. When bugs have been worked out on THORChain end, cap will be raised 👍

**Comment by djesys** [comment]
Hi, thanks for getting back.
So strangely, some hours ago, BTC balance showed up correctly, but now it is showing again 0.
Under the the link you have send me, I can see a “pending_asset” and a “pending_tx_id”.
Unfortunately, the pending_tx_Id is not recognized by any BTC Block explorer, so I cannot follow up on its progress.
Any thoughts on why the balance is fluctuating and now 0 ?

thank you.

**Comment by stuartwk** [comment]
Connected with @djesys, confirmed that this can be closed out
