### ISSUE TITLE
Missing RUNE and BTC after adding liquidity to BTC Pool

### ISSUE THREAD

**Issue by qnnx** [asgardex/asgard-exchange#322]
Well I didn't know where is an issue before I did this, but in ASGARDEX I added 169.19 RUNE and 0.04652754 BTC to the BTC pool, it failed, but I got refunded only 0.041 BTC and 166.80712297 RUNE.

My Thor address
thor159yzrxfwrnrgc78vtymq4plxdtxaal6nzrdyjn

Anything that can be done?

**Comment by stuartwk** [comment]
Hey @qnnx, thanks for reaching out. I contacted the core THORChain devs, they confirmed it was an issue, and they said to reach out to @kkkilo on Telegram to walk you through what to do.

**Comment by qnnx** [comment]
I can't seem to find him. Can you point me to him?

**Comment by TestTestTestikel** [comment]
Same issue here, opened ticket on Discord and got referred to THORChain DEV Telegram. Shared message below there:

Hi team, the Bull referred me to this Telegram after submitting a support ticket on Discord. Hope you guys can help, tried to add liquidity yesterday because RUNE was below the CAP, no mention of cap reach so I thought I could add liquidity. I tried to add BTC but order failed. RUNE returned to wallet but BTC didn't. Order is visible as processed on BTC address but can't be located. Can you someone help me with this?

**Comment by kaiansaari** [comment]
This is expected behavior. A small amount of asset is retained to cover gas costs for the refund.

**Comment by TestTestTestikel** [comment]
Thanks for the response but that wasn't the case. I had pending BTC liquidity but RUNE tx failed due to cap on pools.
I received info below from K which solved it, both RUNE and BTC are visible again in wallets, thanks a million!

**For those with pending assets, please try https://app.asgard.exchange/deposit-sym-recovery.**

this will withdraw ALL of the assets in that pool (both pending and successful). please do not submit multiple times for a pool. if there's an issue with the withdraw, you can create an issue at https://github.com/asgardex/asgard-exchange/issues.
keep in mind, due to some xchain updates, you'll need a minimum of 3 RUNE in your wallet. the withdraw doesn't cost that much, but it's like a safety net to make sure the withdraw tx succeeds.
specifically for BTC, keep in mind that fees are still quite high at the moment
