### ISSUE TITLE
Missing ETH after trying to pool

### ISSUE THREAD

**Issue by jjz216** [asgardex/asgard-exchange#324]
I tried to pool 5.4 ETH in Asgardex, but apparently it was not successful. It says "YOU DON'T HAVE SHARES IN THIS POOL." The ETH have now disappeared from my wallet, and it looks like the RUNE was refunded to me. The ETH was sent to an address. Can you please help me recover the ETH? Thank you. 

<img width="1099" alt="Screen Shot 2021-04-23 at 10 19 45 AM" src="https://user-images.githubusercontent.com/83079071/115884996-7cd0d600-a41d-11eb-8953-625f065043b3.png">
<img width="1100" alt="Screen Shot 2021-04-23 at 10 19 53 AM" src="https://user-images.githubusercontent.com/83079071/115884998-7cd0d600-a41d-11eb-8aba-e0bf1730e251.png">

**Comment by stuartwk** [comment]
Hey @jjz216 👋 , it looks like you're on a different interface. This is the codebase for app.asgard.exchange. If you're on the desktop app, you can file an issue at https://github.com/asgardex/asgard-exchange/pull/214/files#diff-f38049a366060a89ccfe247f9883f3b6f88721151d87c491a8c3c3c1d1115b80. 

FYI, pool caps have not been increased, this is just a small UI bug due to a THORChain update. There was an announcement on the Telegram channel about it.
