### ISSUE TITLE
Different swap fees between Asgardex and ThorSwap?

### ISSUE THREAD

**Issue by kuiper23** [asgardex/asgard-exchange#355]
Hi, I got 2 substantially different quotes for virtually the same transaction today. The AsgarDex tx was much more expensive.

And the AsgarDex quote seemed to have a couple more bugs, but maybe I'm making a noob error of some sort. This is what I'm seeing:

- the warning at the bottom of Asgardex's quote seemed to suggest that tx fees would be greater than the amount received. But this doesn't seem to be the case. Comparing the send amount ($36) and receive amount ($25) suggests tx costs for this swap would be around $11, which is 44% of the output.

- Attempting to calculate the tx cost myself using the quoted network fee (0.0000225 BCH) and BCH's approximate cost at the time (~$890) suggest an entirely different tx cost of $0.02, which is of course very, very inexpensive.

![Screenshot 2021-04-27 205355](https://user-images.githubusercontent.com/81938165/116348077-40490580-a7a2-11eb-89d5-bb8a8481babf.png)

![Screenshot 2021-04-27 205332](https://user-images.githubusercontent.com/81938165/116348079-40e19c00-a7a2-11eb-9451-c0d517422742.png)

**Comment by stuartwk** [comment]
Hey @kuiper23, I believe this is due to AsgardEx subtracting the inbound + outbound network fees from the estimated output. I don't think THORSwap does that. In reality, the actual output will be the same on both apps, it's just an estimation. THORChain itself is what deducts fees, not the UI.

Feel free to take a look at how we're calculating the fee at https://github.com/asgardex/asgard-exchange/blob/master/src/app/_services/transaction-utils.service.ts#L50

The rate is pulled from https://midgard.thorchain.info/v2/thorchain/inbound_addresses, usually BCH is 3 sats/byte.

We're still working on standardizing estimated fees, and we'll probably be following the asgardex desktop app for this. There's an issue here you can follow along at https://github.com/asgardex/asgard-exchange/issues/348.
