### ISSUE TITLE
Missing ETH after failed RUNE exchange

### ISSUE THREAD

**Issue by code-ae** [asgardex/asgard-exchange#371]
I am currently experiencing the same issue listed in this issue.https://github.com/asgardex/asgard-exchange/issues/280?fbclid=IwAR11a1H3fqWLzR82yPAsgVtIcs0sEvjdCafFBbfSSbykTFINiP7hXOWdMcE

I am having trouble connecting my Asgardex wallet to the '/deposit-sym-recovery' page.
Please advise on how i can proceed, appreciate any information, thank you.

**Comment by stuartwk** [comment]
Hey @code-ae 👋, you can check if there is a stuck pending deposit at [https://app.asgard.exchange/deposit-sym-recovery](https://app.asgard.exchange/deposit-sym-recovery).

- Connect your wallet on the deposit-sym-recovery page.
- Click "Search Pool"
- In your case, select ETH
- If you have pending assets stuck, it will show an amount that is missing. Since markets are capped right now, your option will be to withdraw funds. Just keep in mind, this will also withdraw any previously successfully deposited ETH as well. You must have at least 3 RUNE in your wallet. This is used as a safety net to ensure the RUNE withdraw tx succeeds. 

If it says "no missing deposit found", please share your ETH address, and we can try and track down what went wrong.

**Comment by stuartwk** [comment]
Closing this out. If you're still having issues, feel free to open a new issue.
