### ISSUE TITLE
Error when removing liquidity

### ISSUE THREAD

**Issue by magari7** [asgardex/asgard-exchange#412]
When trying to remove liquidity from thorchain (BUSD pool) I get an error saying that "Min 3 RUNE in Wallet Required", even though the fees are clearly stated to be 0.02 RUNE only. I have less than 3 RUNE in my wallet and as a result I cannot withdraw even though I have enough RUNE for the fees.

![Screenshot](https://user-images.githubusercontent.com/85957707/122097737-4ce7f280-ce10-11eb-8ec4-3c64ef6c9b0a.png)

**Comment by stuartwk** [comment]
Hey @magari7 👋, this is due to the keystore library we're using XChain. It was recommended by one of the core THORChain devs that users keep at least 3 RUNE in wallet to ensure transactions process. We were previously having issues with failed RUNE transactions, even though users had the RUNE tx fee amount in their wallet. These are essentially growing pains, as more wallets are added and XChain + THORChain mature, this will be removed.
