### ISSUE TITLE
Made a trade and didn’t receive funds 

### ISSUE THREAD

**Issue by sergioselva** [asgardex/asgard-exchange#435]
I made a swap on the LTC blockchain for RUNE on ASGARDEX.I never got my RUNE but lost all my LTC. Tarde was placed on 7/30/21 prior to the newest update version of ASGARDEX.Please help

**Comment by stuartwk** [comment]
Hello, the THORChain network is down at the moment. Funds should be received once the network is back online. You can follow along about the state of the network on their Twitter or Discord. Additionally, I believe you're on the desktop app, since you're referring to the version update. This is for the web app, the desktop repo can be found at https://github.com/thorchain/asgardex-electron.

**Comment by sergioselva** [comment]
Hey Stuart,

Thanks for reaching out to it really means a lot. I’ve been using ASGARDX on a Mac. The price for RUNE according to ASGARDX has been $4.71 for quite some time so I could tell something was up. It’s also concerning that when I go into my trade history I cannot track the trade. Do you have any guess in the time table as to when this will be fixed?

Best,

Sergio Selva

**Comment by sergioselva** [comment]
I use the Mac desktop. It’s still down and my funds are still missing please help!
