### ISSUE TITLE
Rune and BTC gone after trying to add liquidity

### ISSUE THREAD

**Issue by pistolstamen** [asgardex/asgard-exchange#90]
Here is what happened. Got my test rune fine. Converted it to native rune fine. swapped 50% to BTC fine. Tried to add to the pool. Now it shows I have nothing in the pool, I have my .05 BTC but only 1.5 Rune.

![Image 2-8-21 at 5 30 PM](https://user-images.githubusercontent.com/78769136/107303340-b9527f80-6a33-11eb-83bb-2cb089371e7e.jpeg)
![Image 2-8-21 at 5 31 PM](https://user-images.githubusercontent.com/78769136/107303341-b9527f80-6a33-11eb-89a9-a33bc5244fdf.jpeg)

**Comment by pistolstamen** [comment]
Actually, BTC gone, too. I still have some BTC because the price of BTC was going crazy when I swapped half of my Rune for BTC so there is some left when I added to the pool. Both assets gone.

**Comment by pistolstamen** [comment]
I've seen it suggested that its due to bitcoin transactions taking a long time...well, one, this never resolved and two, when I was watching the transactions, the BTC one showed that it went through while the RUNE one was the one that was pending until failure.

**Comment by stuartkuentzel** [comment]
This could be any number of issues. We've updated our Bitcoin API provider, so it might have had to do something with slow processing on Blockchair. The network has also gone through a reset, which would reset what is pooled. Additionally, we recently changed the way we're displaying and polling pending transactions. I just tested and was able to deposit and withdraw RUNE + BTC. Closing for now, but if it reoccurs, feel free to open another issue, and please add a transaction ID, otherwise it's impossible for us to trace.
