### ISSUE TITLE
Incorrect prices shown

### ISSUE THREAD

**Issue by Riksis** [asgardex/asgard-exchange#99]
Trying to swap from THOR.RUNE to BUSD, inputting 100Rune should output around 400BUSD but instead it outputs 3BUSD and says 25 RUNE for 1 USD so either this price is wrong or the estimated balance is incorrect.
![thorbusd](https://user-images.githubusercontent.com/78785438/107331389-447f5400-6acc-11eb-8b63-aca1eeaf7297.JPG)

bnb180ehlydt7qtfghluvjqlv9gza5ug09cx35nxjh

**Comment by stuartkuentzel** [comment]
Hey @Riksis, this is being brought up a lot. The testnet THORChain network prices aren't going to reflect mainnet prices. Pools are going to be way differently balanced. If you go through with the transaction, you'll see that the output you receive is close to the estimated output. Closing this since it's the nature the the THORChain testnet network pools, not an interface issue.
